### ISSUE TITLE
Implement Transactions Screen

### ISSUE THREAD

**Issue by jleesCY** [davisssamuel/notis#26]
If you would like to use previous JSX code and CSS for reference:
[JSX](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/components/mobile/MobileTransactionHistory.js)
[CSS](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/css/mobile/MobileTransactionHistory.css)

If you want to use my [SVGs](https://github.com/davisssamuel/notis/tree/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/images/svg) at all go ahead

**Comment by lukelyall** [comment]
I have a rough transaction history page made. Similar to the chat list, it uses a .json file. The .json file includes the type of transaction, name associated with the transaction, amount, timestamp, and note about the transaction. The header, return buttons, and CSS still need more work.

**Comment by lukelyall** [comment]
Fixed some CSS and created clickable names that will bring you to the contacts page

**Comment by lukelyall** [comment]
Made changes to the CSS to make it look like our previous transaction page
