### ISSUE TITLE
Implement Login Screen

### ISSUE THREAD

**Issue by jleesCY** [davisssamuel/notis#28]
If you would like to use previous JSX code and CSS for reference:
[JSX](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/components/mobile/MobileLogin.js)
[CSS](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/css/mobile/MobileLogin.css)

If you want to use my [SVGs](https://github.com/davisssamuel/notis/tree/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/images/svg) at all go ahead

**Comment by lukelyall** [comment]
Very basic beginning. Created the page and started work on the css and header.

**Comment by lukelyall** [comment]
Added a pressable generate button and a text field for a private key.

**Comment by lukelyall** [comment]
Started work on a basic popup and added a login button that navigates to the contact screen when clicked
