### ISSUE TITLE
Implement Contact Details Screen

### ISSUE THREAD

**Issue by jleesCY** [davisssamuel/notis#30]
If you would like to use previous JSX code and CSS for reference:
[JSX](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/components/mobile/MobileContact.js)
[CSS](https://github.com/davisssamuel/notis/blob/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/css/mobile/MobileContact.css)

If you want to use my [SVGs](https://github.com/davisssamuel/notis/tree/43f70c44205d2fddb661bd9de0c01c8e21a9ebbd/code/frontend/src/images/svg) at all go ahead

**Comment by davisssamuel** [comment]
Dependent on Contacts List Screen
