### ISSUE TITLE
Fix login key copying

### ISSUE THREAD

**Issue by jleesCY** [davisssamuel/notis#43]

**Comment by lukelyall** [comment]
- Switched library to expo-clipboard
- used setStringAsync

**Comment by jleesCY** [comment]
- Add some sort of error handling to the function call
`Clipboard.setStringAsync(privateKey)`

**Comment by lukelyall** [comment]
Added error handling for if the copy fails. Also, added a new temporary modal that states to the user whether the copy worked or failed.
